apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cdim-layout-apply
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./secrets/secrets.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "true"